[package]
name = "OMock"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-web-codegen = "4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.1", features = ["v4", "serde"] }
actix-files = "0.6"
env_logger = "0.9"
log = "0.4"
