apiVersion: apps/v1
kind: Deployment
metadata:
  name: omock-deployment
  labels:
    app: omock
spec:
  replicas: 2
  selector:
    matchLabels:
      app: omock
  template:
    metadata:
      labels:
        app: omock
    spec:
      containers:
        - name: omock
          image: pothiq/fastmock:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: APP_LABEL
              value: "omock"
            # Metrics are disabled by default
            - name: METRICS_ENABLED
              value: "false"
            # Uncomment the following lines to enable metrics
            # - name: METRICS_ENABLED
            #   value: "true"
            # - name: METRICS_PORT
            #   value: "9090"
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
