apiVersion: v1
kind: Service
metadata:
  name: omock-headless
  labels:
    app: omock
spec:
  clusterIP: None  # Headless service
  selector:
    app: omock
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
